base_dir: "/opt/podman-builds"
image_tag: "v1"

build_images_list:
  - name: nginx
    dockerfile: |
      FROM registry.access.redhat.com/ubi9/nginx-124:latest
      LABEL maintainer="security@test.local"

      USER 1001

      EXPOSE 8080

      CMD ["nginx", "-g", "daemon off;"]

  - name: tomcat
    dockerfile: |
      FROM registry.access.redhat.com/ubi9/ubi
      LABEL maintainer="security@test.local"
      # Install Java 17 and tools
      RUN dnf install -y java-17-openjdk wget unzip && \
          dnf clean all
      # Install old Tomcat manually
      ENV TOMCAT_VERSION=9.0.108
      RUN wget https://archive.apache.org/dist/tomcat/tomcat-9/v${TOMCAT_VERSION}/bin/apache-tomcat-${TOMCAT_VERSION}.tar.gz && \
          tar -xvzf apache-tomcat-${TOMCAT_VERSION}.tar.gz && \
          mv apache-tomcat-${TOMCAT_VERSION} /opt/tomcat && \
          rm apache-tomcat-${TOMCAT_VERSION}.tar.gz
      EXPOSE 8080
      CMD ["/opt/tomcat/bin/catalina.sh", "run"]

  - name: java
    dockerfile: |
      FROM registry.access.redhat.com/ubi9/openjdk-17-runtime:latest
      LABEL maintainer="security@test.local"

      USER 1001

      CMD ["java", "-version"]

  - name: ansible
    dockerfile: |
      FROM registry.access.redhat.com/ubi9/ubi
      LABEL maintainer="security@test.local"
      
      USER root
      RUN dnf install -y python3-pip rust-toolset openssl-devel python3-devel && \
          pip3 install setuptools_rust && \
          pip3 install ansible-core && \
          dnf clean all 
      USER nobody    
      CMD [ "ansible", "--version" ]





