base_dir: "/opt/podman-builds"
image_tag: "v1"

build_images_list:
  - name: nginx
    dockerfile: |
      FROM registry.access.redhat.com/ubi9/nginx-124:latest
      LABEL maintainer="security@test.local"

      USER 1001

      EXPOSE 8080

      CMD ["nginx", "-g", "daemon off;"]

  - name: tomcat
    dockerfile: |
      FROM registry.access.redhat.com/ubi9/openjdk-17-runtime:latest
      LABEL maintainer="security@test.local"

      ARG TOMCAT_VERSION=9.0.108
      ENV CATALINA_HOME=/opt/tomcat
      ENV PATH="${CATALINA_HOME}/bin:${PATH}"
      
      USER root 

      RUN dnf -y update && dnf -y install tar gzip \
          && curl -fsSL "https://dlcdn.apache.org/tomcat/tomcat-9/v${TOMCAT_VERSION}/bin/apache-tomcat-${TOMCAT_VERSION}.tar.gz" -o /tmp/tomcat.tgz \
          && mkdir -p "${CATALINA_HOME}" \
          && tar -xzf /tmp/tomcat.tgz -C /opt \
          && mv /opt/apache-tomcat-${TOMCAT_VERSION}/* "${CATALINA_HOME}/" \
          && rm -rf /tmp/tomcat.tgz /opt/apache-tomcat-${TOMCAT_VERSION} \
          && dnf -y remove curl tar gzip && dnf clean all

      RUN chgrp -R 0 "${CATALINA_HOME}" && chmod -R g=u "${CATALINA_HOME}"
      USER 1001

      EXPOSE 8080
      CMD ["catalina.sh", "run"]


  - name: java
    dockerfile: |
      FROM registry.access.redhat.com/ubi9/openjdk-17-runtime:latest
      LABEL maintainer="security@test.local"

      USER 1001

      CMD ["java", "-version"]

  - name: ansible
    dockerfile: |
      FROM registry.access.redhat.com/ubi9/python-311:latest
      LABEL maintainer="security@test.local"
      
      USER root
      RUN dnf -y update && dnf clean all && \
          pip3 install --no-cache-dir --upgrade "ansible-core>=2.17,<2.18"

      USER 1001

      CMD ["ansible", "--version"]



